"""Generate Mermaid text and the trace table from validated diagram IR.

``python -m engine diagrams generate`` writes, per document directory:

* ``_generated/<FIG-nnn>.mmd`` — Mermaid for Markdown previews and as input to
  the M10-01 renderer (``scripts/render_diagrams.py``);
* ``_generated/trace-table.md`` — Figure, Element, Kind, Requirement IDs, SRS
  section; derived, never hand-edited (replaces the hand-typed HLD Step 11
  table);
* ``_generated/.generated.json`` — IR and Mermaid hashes per figure.

Output is canonical (elements sorted by id; messages by order then id; LF line
endings), so two runs over the same IR are byte-identical. Every ``.mmd``
starts with an ``%%{init}%%`` directive whose ``fontFamily`` is
``DIAGRAM_FONT_STACK``. That value applies the design engine's diagram
standard (chwezi-design-engine
``skills/13-presentations-and-documents/docx-report-and-document-formatting/references/diagram-visual-standards.md``):
Public Sans for diagram labels in formal documents, written unquoted because
Mermaid drops a ``fontFamily`` value that contains quote characters (M10-01
spike finding). It must equal the renderer's ``render-config.json`` stack;
a test pins that.

Context and component figures are emitted as ``flowchart LR`` with subgraphs
for boundaries (Mermaid's C4 forms give weak layout and font control).

Pattern adapted from Archify (MIT, https://github.com/tt-a1i/archify, commit
0e4949f910a8e390bd3b4933883a4dcabad571be). Paraphrased; no schema, code or
test text copied.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Tuple

from engine.diagram_ir import (
    GENERATED_DIR,
    GENERATED_NAME,
    TRACE_TABLE_NAME,
    DiagramIR,
    Diagnostic,
    load_doc_irs,
    text_sha256,
    unvalidated,
)

# Diagram label face from diagram-visual-standards.md (design engine, AR-12).
DIAGRAM_FONT_STACK = "Public Sans, sans-serif"
MERMAID_THEME = "neutral"
GENERATED_BANNER = "Generated by `python -m engine diagrams generate`; do not edit."


def init_directive() -> str:
    return "%%{init: " + json.dumps(
        {"theme": MERMAID_THEME, "themeVariables": {"fontFamily": DIAGRAM_FONT_STACK}}
    ) + "}%%"


# -- label and id escaping ----------------------------------------------------------

def _text(value: str) -> str:
    """Mermaid-safe label text (entity codes for characters Mermaid parses)."""
    codes = {"#": "#35;", ";": "#59;", '"': "#quot;", "<": "#lt;", ">": "#gt;",
             "|": "#124;", "{": "#123;", "}": "#125;", "\n": " ", "\r": ""}
    return "".join(codes.get(ch, ch) for ch in str(value))


def _mid(prefix: str, element_id: str) -> str:
    return f"{prefix}_{element_id.replace('-', '_')}"


def _check_ids(ir: DiagramIR, prefix: str) -> Dict[str, str]:
    mapping: Dict[str, str] = {}
    used: Dict[str, str] = {}
    for el in ir.nodes + ir.boundaries:
        mid = _mid(prefix, el["id"])
        if mid in used and used[mid] != el["id"]:
            raise ValueError(f"{ir.figure_id}: ids '{used[mid]}' and '{el['id']}' collide "
                             "in Mermaid; rename one")
        used[mid] = el["id"]
        mapping[el["id"]] = mid
    return mapping


# -- per-kind emitters ----------------------------------------------------------------

_FLOW_SHAPES = {
    "system": ('["', '"]'), "component": ('["', '"]'), "node": ('["', '"]'),
    "process": ('("', '")'), "zone": ('["', '"]'),
    "person": ('(["', '"])'), "external_system": ('[/"', '"/]'), "external": ('[/"', '"/]'),
    "external_entity": ('[/"', '"/]'),
    "datastore": ('[("', '")]'), "store": ('[("', '")]'), "queue": ('>"', '"]'),
}


def _flowchart(ir: DiagramIR) -> List[str]:
    ids = _check_ids(ir, "n")
    lines = ["flowchart LR"]
    nodes = sorted(ir.nodes, key=lambda n: n["id"])
    by_boundary: Dict[str, List[dict]] = {}
    free: List[dict] = []
    for n in nodes:
        (by_boundary.setdefault(n["boundary"], []) if n.get("boundary") else free).append(n)

    def node_line(n: dict, indent: str) -> str:
        left, right = _FLOW_SHAPES.get(n["role"], ('["', '"]'))
        return f"{indent}{ids[n['id']]}{left}{_text(n['label'])}{right}"

    for b in sorted(ir.boundaries, key=lambda x: x["id"]):
        lines.append(f'  subgraph {_mid("b", b["id"])}["{_text(b["label"])}"]')
        for n in by_boundary.get(b["id"], []):
            lines.append(node_line(n, "    "))
        lines.append("  end")
    known_boundaries = {b["id"] for b in ir.boundaries}
    for bid, members in sorted(by_boundary.items()):
        if bid not in known_boundaries:
            free.extend(members)
    for n in sorted(free, key=lambda x: x["id"]):
        lines.append(node_line(n, "  "))
    for e in sorted(ir.edges, key=lambda x: (x.get("order", 0), x["id"])):
        if e["from"] not in ids or e["to"] not in ids:
            continue
        arrow = "-.->" if e.get("kind") == "async" else "-->"
        label = f'|"{_text(e["label"])}"|' if e.get("label") else ""
        lines.append(f"  {ids[e['from']]} {arrow}{label} {ids[e['to']]}")
    return lines


def _sequence(ir: DiagramIR) -> List[str]:
    ids = _check_ids(ir, "p")
    lines = ["sequenceDiagram"]
    # Participants keep authored order so the reading order is the author's.
    for n in ir.nodes:
        lines.append(f"  participant {ids[n['id']]} as {_text(n['label'])}")
    arrows = {"sync": "->>", "async": "-)", "return": "-->>"}
    for e in sorted(ir.edges, key=lambda x: (x.get("order", 0), x["id"])):
        if e["from"] not in ids or e["to"] not in ids:
            continue
        label = _text(e.get("label", e["id"]))
        lines.append(f"  {ids[e['from']]}{arrows.get(e.get('kind', 'sync'), '->>')}"
                     f"{ids[e['to']]}: {label}")
    return lines


def _state(ir: DiagramIR) -> List[str]:
    ids = _check_ids(ir, "s")
    lines = ["stateDiagram-v2"]
    for n in sorted(ir.nodes, key=lambda x: x["id"]):
        lines.append(f'  state "{_text(n["label"])}" as {ids[n["id"]]}')
    for n in sorted(ir.nodes, key=lambda x: x["id"]):
        if n["role"] == "start":
            lines.append(f"  [*] --> {ids[n['id']]}")
    for e in sorted(ir.edges, key=lambda x: (x.get("order", 0), x["id"])):
        if e["from"] not in ids or e["to"] not in ids:
            continue
        label = f": {_text(e['label'])}" if e.get("label") else ""
        lines.append(f"  {ids[e['from']]} --> {ids[e['to']]}{label}")
    for n in sorted(ir.nodes, key=lambda x: x["id"]):
        if n["role"] == "terminal":
            lines.append(f"  {ids[n['id']]} --> [*]")
    return lines


_CARDINALITY = {"1:1": "||--||", "1:N": "||--o{", "N:M": "}o--o{", "0..1:N": "|o--o{"}


def _entity_name(element_id: str) -> str:
    return element_id.upper().replace("-", "_")


def _erd(ir: DiagramIR) -> List[str]:
    names = {n["id"]: _entity_name(n["id"]) for n in ir.nodes}
    lines = ["erDiagram"]
    for n in sorted(ir.nodes, key=lambda x: x["id"]):
        lines.append(f'  {names[n["id"]]}["{_text(n["label"])}"] {{')
        for a in n.get("attributes", []):
            key = {"pk": " PK", "fk": " FK"}.get(a["key"], "")
            lines.append(f"    {a['type']} {a['name']}{key}")
        lines.append("  }")
    for e in sorted(ir.edges, key=lambda x: (x.get("order", 0), x["id"])):
        if e["from"] not in names or e["to"] not in names:
            continue
        label = _text(e.get("label", e["id"]))
        lines.append(f'  {names[e["from"]]} {_CARDINALITY[e["cardinality"]]} '
                     f'{names[e["to"]]} : "{label}"')
    return lines


_EMITTERS = {
    "context": _flowchart, "component": _flowchart, "deployment": _flowchart,
    "dataflow": _flowchart, "sequence": _sequence, "state": _state, "erd": _erd,
}


def to_mermaid(ir: DiagramIR) -> str:
    """Mermaid text for one valid IR, starting with the approved-font directive."""
    body = _EMITTERS[ir.kind](ir)
    return "\n".join([init_directive(), *body]) + "\n"


# -- trace table ---------------------------------------------------------------------

def _element_kind(ir: DiagramIR, etype: str, el: dict) -> str:
    if etype == "node":
        return f"{ir.kind}/{el['role']}"
    if etype == "edge":
        sub = "message" if ir.kind == "sequence" else (
            "transition" if ir.kind == "state" else (
                "relationship" if ir.kind == "erd" else "flow"))
        return f"{ir.kind}/{sub}"
    return f"{ir.kind}/boundary"


def _cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def trace_table(irs: List[DiagramIR]) -> str:
    """Markdown trace table for the figures of one document (canonical order)."""
    lines = [
        "<!-- " + GENERATED_BANNER + " -->",
        "",
        "| Figure | Element | Kind | Requirement IDs | SRS section |",
        "|---|---|---|---|---|",
    ]
    for ir in sorted(irs, key=lambda i: i.figure_id):
        section = ir.meta.get("srs_section", "")
        for etype, el in ir.elements():
            label = el.get("label") or el["id"]
            trace = ", ".join(sorted(el.get("trace", []))) or "—"
            lines.append(f"| {ir.figure_id} | {_cell(label)} (`{el['id']}`) | "
                         f"{_element_kind(ir, etype, el)} | {trace} | {section} |")
    return "\n".join(lines) + "\n"


# -- generate --------------------------------------------------------------------------

def generate(doc_dir: Path) -> Tuple[Dict[str, Path], List[Diagnostic]]:
    """Write Mermaid, trace table and hash record for one document directory.

    Refuses (returns diagnostics, writes nothing) when any IR is invalid or is
    not the candidate accepted by the last ``diagrams validate``.
    """
    doc_dir = Path(doc_dir)
    irs, diags = load_doc_irs(doc_dir)
    if diags:
        return {}, diags
    frozen = unvalidated(doc_dir, irs)
    if frozen:
        return {}, frozen
    out_dir = doc_dir / GENERATED_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    written: Dict[str, Path] = {}
    record: Dict[str, dict] = {}
    for ir in sorted(irs, key=lambda i: i.figure_id):
        text = to_mermaid(ir).encode("utf-8")
        path = out_dir / f"{ir.figure_id}.mmd"
        path.write_bytes(text)
        written[ir.figure_id] = path
        record[ir.figure_id] = {"ir_path": ir.path.relative_to(doc_dir).as_posix(),
                                "ir_sha256": ir.sha256,
                                "mermaid": path.name,
                                "mermaid_sha256": text_sha256(text)}
    table = out_dir / TRACE_TABLE_NAME
    table.write_bytes(trace_table(irs).encode("utf-8"))
    written["trace-table"] = table
    (out_dir / GENERATED_NAME).write_bytes((json.dumps(
        {"schema": "srs-diagram-generated/1", "note": GENERATED_BANNER,
         "font_family": DIAGRAM_FONT_STACK, "figures": record,
         "trace_table_sha256": text_sha256(table.read_bytes())},
        indent=2, sort_keys=True) + "\n").encode("utf-8"))
    return written, []
